Dictionary correction in the "season" section
anilibria/docs pull request #22
Opened 2022-11-18 08:13 UTC by IlyaKotomin

I corrected the typos at lines 948 and 949

2022-12-26 00:53 UTC, T1MOXA commented on api_v2.md
> +* В случае если ключ указан не верно торрент клинет будет возвращать ошибку о неправильном формате торрента.
*клиент

2022-12-26 00:55 UTC, T1MOXA requested changes
Спасибо за исправления, все по делу.
К сожалению я нашел 1 опечатку в вашем комите, в слове клиент
По возможности исправьте опечатку и я смогу принять изменения.

2022-12-29 20:16 UTC, IlyaKotomin commented
Проверьте

2023-01-05 22:14 UTC, T1MOXA approved these changes

2023-01-05 22:20 UTC, merged